name: to-pages
on:
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - name: Deploy
      run : |
          origin=$(git config --get remote.origin.url)
          echo "$origin"
          cd dist
          git init
          git add .
          git commit -m 'Deploy'
          git remote add origin "$origin"
          git push -f origin master:gh-pages
          cd ..

# EOF
